### PR TITLE
Fix exception when being run with simplecov >0.20.0 and no coverage

### PR DESCRIPTION
**Pull request by dsander**
Older simplecov versions always returned result even if no coverage
information was present. Since [version 0.20.0][1] `merged_result` will
be `nil` is no coverage information was available.

[1]: https://github.com/simplecov-ruby/simplecov/commit/20ddc387b7b476cf00e28544d1d10727f7709986#diff-0214a0da6c212d3cf4fe55027ea17aa13adf5d2dfe0eb3812c28bddbf3d431b4R94

-------------------------------------------------
Loosen rake development dependency versions

Fixes https://github.com/advisories/GHSA-jppv-gw3r-w3q8

### CODE REVIEW

**Comment by bradrees** [comment]
We've just seen our CI build process fail with this error, great work on getting a fix out so fast!

**Review by bradrees — APPROVED** [review]

**Review by bradrees — COMMENTED** [review]
Bump the version too: https://github.com/dsander/pronto-simplecov/blob/a8c6436587a6fa00803caadb6c34a75a7780d216/lib/pronto/pronto_simplecov/version.rb#L3

**Comment by dsander** [comment]
> Bump the version too:

Thanks for the reminder, I'll bump the version on master 😄

**Comment by dsander** [comment]
Released as `0.10.1`

**Pull request merged**
